FROM python:3.10
ARG METHOD="openai"
ARG ENV_NAME="my_env"
ARG PYTHON_VER="3.10"

RUN mkdir settings
COPY requirements_core.txt install_dependencies_core.sh ./settings/
RUN bash ./settings/install_dependencies_core.sh $ENV_NAME $PYTHON_VER $METHOD

COPY requirements_${METHOD}.txt install_dependencies_other.sh ./settings/
RUN bash ./settings/install_dependencies_other.sh $ENV_NAME transformers
